### PR TITLE
Entries

### PR DESCRIPTION
**Pull request by joaop21**
Add a new field to attendee which represents the number of entries that he/she has for the final draw.
This entries can be won when a badge is redeemed. Normal badges give 1 entry.

Resolves: #170

### CODE REVIEW

**Comment by jpcorreia99** [comment]
Shouldn't there also be a task to randomly chose a winner?

**Comment by joaop21** [comment]
> Shouldn't there also be a task to randomly chose a winner?

It was not made explicit whether we are the ones who will implement the final draw.

**Comment by jpcorreia99** [comment]
Okay, it's better that we talk to the managers to make that clear. Either way, that won't have an impact in this code, so I'll approve it.

**Review by jpcorreia99 — APPROVED** [review]

**Comment by joaop21** [comment]
Possibly we will have to export the attendees with their number of entries.

**Pull request merged**
