### PR TITLE
Add capability to mark redeems as redeemed

### PR DESCRIPTION
**Pull request by DrPeterPun**

### CODE REVIEW

**Comment by jtexeira** [comment]
@DrPeterPun you forgot to create the migration to actually add the new field to the database schema.
My last commit was to add it if you want to check it. I know it is a bit misleading the way this works, since we have to write the schema twice.
Here is how you generate migrations for the next time it's needed: https://hexdocs.pm/ecto_sql/Ecto.Migration.html

**Review by jtexeira — CHANGES_REQUESTED** [review]
`** (UndefinedFunctionError) function SafiraWeb.DeliverRedeemableController.init/1 is undefined (module SafiraWeb.DeliverRedeemableController is not available)`
Acho que te falta o ficheiro do Controller

**Comment by DrPeterPun** [comment]
the file exists but somehow ended up on the wrong place, /safira_web instead of /safira_web/controllers

**Comment by DrPeterPun** [comment]
the previous commit was made with "commit -am" witch does not add new files, should be fixed now

**Review by jtexeira — DISMISSED** [review]

**Comment by jtexeira** [comment]
IT WORKS :tada:

**Review by jtexeira — APPROVED** [review]

**Pull request merged**
