### PR TITLE
feat: migrate badge gifting tasks to cron-like jobs

### LINKED ISSUE #340: Convert badge giving tasks to quantum jobs

### PR DESCRIPTION
**Pull request by ruilopesm**
Closes #340.

### CODE REVIEW

**Comment by ruilopesm** [comment]
Requires #356 to be merged first.

**Review by ruioliveira02 — COMMENTED** [review]
I like this approach. Sometimes you just need something simple that works, and this is a good example of that.

**Comment by diogogmatos** [comment]
[feat: migrate badge gifting tasks to cron-like jobs](https://trello.com/c/o6tTZUYZ/24-feat-migrate-badge-gifting-tasks-to-cron-like-jobs)

**Review by ruioliveira02 — APPROVED** [review]
The PR works. We will have to adjust tasks later on so for now this is perfect :rocket:

**Pull request merged**
